spring.application.name=conference-planner

# DevTools: restart when classpath changes (e.g. after recompile on save)
spring.devtools.restart.enabled=true

server.port=8080

app.name=Conference Planner
app.seeding=false